### PR TITLE
Added support for spesifiy full url

### PR DESCRIPTION
**Pull request by gerhardsletten**
Hi, have a use-case where where piwik is running on ssl, but the frontend app is not (in dev-mode), so added the possibility to specify http/https in the url

### CODE REVIEW

**Comment by joernroeder** [comment]
Hey, yes, this looks like a tiny but necessary improvement when dealing switching between http/https in development and production. Would you mind adding a note to the readme which explains the change?

**Comment by gerhardsletten** [comment]
@joernroeder Now it should be added

**Comment by joernroeder** [comment]
@gerhardsletten hey cool, thanks! i've published a new version to npm as well!

**Comment by gerhardsletten** [comment]
Great, thanks

G

**Pull request merged**
